# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pref.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(685, 350)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(685, 350))
        Form.setMaximumSize(QtCore.QSize(685, 350))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setMinimumSize(QtCore.QSize(111, 0))
        self.frame.setMaximumSize(QtCore.QSize(111, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.hLayout_gen = QtWidgets.QHBoxLayout()
        self.hLayout_gen.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.hLayout_gen.setObjectName("hLayout_gen")
        self.lbl_nav_gen = QtWidgets.QLabel(self.frame)
        self.lbl_nav_gen.setMinimumSize(QtCore.QSize(6, 24))
        self.lbl_nav_gen.setMaximumSize(QtCore.QSize(6, 24))
        self.lbl_nav_gen.setStyleSheet("background-color:#4E5764;")
        self.lbl_nav_gen.setText("")
        self.lbl_nav_gen.setObjectName("lbl_nav_gen")
        self.hLayout_gen.addWidget(self.lbl_nav_gen)
        spacerItem1 = QtWidgets.QSpacerItem(40, 24, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hLayout_gen.addItem(spacerItem1)
        self.btn_nav_gen = QtWidgets.QPushButton(self.frame)
        self.btn_nav_gen.setMinimumSize(QtCore.QSize(75, 23))
        self.btn_nav_gen.setMaximumSize(QtCore.QSize(75, 23))
        self.btn_nav_gen.setStyleSheet("border-style:None;\n"
"text-align: left center;")
        self.btn_nav_gen.setObjectName("btn_nav_gen")
        self.hLayout_gen.addWidget(self.btn_nav_gen)
        self.verticalLayout_2.addLayout(self.hLayout_gen)
        self.hLayout_ui = QtWidgets.QHBoxLayout()
        self.hLayout_ui.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.hLayout_ui.setObjectName("hLayout_ui")
        self.lbl_nav_ui = QtWidgets.QLabel(self.frame)
        self.lbl_nav_ui.setMinimumSize(QtCore.QSize(6, 24))
        self.lbl_nav_ui.setMaximumSize(QtCore.QSize(6, 24))
        self.lbl_nav_ui.setStyleSheet("background-color:#4E5764;")
        self.lbl_nav_ui.setText("")
        self.lbl_nav_ui.setObjectName("lbl_nav_ui")
        self.hLayout_ui.addWidget(self.lbl_nav_ui)
        spacerItem2 = QtWidgets.QSpacerItem(40, 24, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hLayout_ui.addItem(spacerItem2)
        self.btn_nav_ui = QtWidgets.QPushButton(self.frame)
        self.btn_nav_ui.setMinimumSize(QtCore.QSize(75, 23))
        self.btn_nav_ui.setMaximumSize(QtCore.QSize(75, 23))
        self.btn_nav_ui.setStyleSheet("border-style:None;\n"
"text-align: left center;")
        self.btn_nav_ui.setObjectName("btn_nav_ui")
        self.hLayout_ui.addWidget(self.btn_nav_ui)
        self.verticalLayout_2.addLayout(self.hLayout_ui)
        self.hLayout_directories = QtWidgets.QHBoxLayout()
        self.hLayout_directories.setObjectName("hLayout_directories")
        self.lbl_nav_directories = QtWidgets.QLabel(self.frame)
        self.lbl_nav_directories.setMinimumSize(QtCore.QSize(6, 24))
        self.lbl_nav_directories.setMaximumSize(QtCore.QSize(6, 24))
        self.lbl_nav_directories.setStyleSheet("background-color:#4E5764;")
        self.lbl_nav_directories.setText("")
        self.lbl_nav_directories.setObjectName("lbl_nav_directories")
        self.hLayout_directories.addWidget(self.lbl_nav_directories)
        spacerItem3 = QtWidgets.QSpacerItem(40, 24, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hLayout_directories.addItem(spacerItem3)
        self.btn_nav_directories = QtWidgets.QPushButton(self.frame)
        self.btn_nav_directories.setMinimumSize(QtCore.QSize(75, 23))
        self.btn_nav_directories.setMaximumSize(QtCore.QSize(75, 23))
        self.btn_nav_directories.setStyleSheet("border-style:None;\n"
"text-align: left center;")
        self.btn_nav_directories.setObjectName("btn_nav_directories")
        self.hLayout_directories.addWidget(self.btn_nav_directories)
        self.verticalLayout_2.addLayout(self.hLayout_directories)
        self.hLayout_browser = QtWidgets.QHBoxLayout()
        self.hLayout_browser.setObjectName("hLayout_browser")
        self.lbl_nav_browser = QtWidgets.QLabel(self.frame)
        self.lbl_nav_browser.setMinimumSize(QtCore.QSize(6, 24))
        self.lbl_nav_browser.setMaximumSize(QtCore.QSize(6, 24))
        self.lbl_nav_browser.setStyleSheet("background-color:#4E5764;")
        self.lbl_nav_browser.setText("")
        self.lbl_nav_browser.setObjectName("lbl_nav_browser")
        self.hLayout_browser.addWidget(self.lbl_nav_browser)
        spacerItem4 = QtWidgets.QSpacerItem(40, 24, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hLayout_browser.addItem(spacerItem4)
        self.btn_nav_browser = QtWidgets.QPushButton(self.frame)
        self.btn_nav_browser.setMinimumSize(QtCore.QSize(75, 23))
        self.btn_nav_browser.setMaximumSize(QtCore.QSize(75, 23))
        self.btn_nav_browser.setStyleSheet("border-style:None;\n"
"text-align: left center;")
        self.btn_nav_browser.setObjectName("btn_nav_browser")
        self.hLayout_browser.addWidget(self.btn_nav_browser)
        self.verticalLayout_2.addLayout(self.hLayout_browser)
        self.hLayout_network = QtWidgets.QHBoxLayout()
        self.hLayout_network.setObjectName("hLayout_network")
        self.lbl_nav_network = QtWidgets.QLabel(self.frame)
        self.lbl_nav_network.setMinimumSize(QtCore.QSize(6, 24))
        self.lbl_nav_network.setMaximumSize(QtCore.QSize(6, 24))
        self.lbl_nav_network.setStyleSheet("background-color:#4E5764;")
        self.lbl_nav_network.setText("")
        self.lbl_nav_network.setObjectName("lbl_nav_network")
        self.hLayout_network.addWidget(self.lbl_nav_network)
        spacerItem5 = QtWidgets.QSpacerItem(40, 24, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hLayout_network.addItem(spacerItem5)
        self.btn_nav_network = QtWidgets.QPushButton(self.frame)
        self.btn_nav_network.setMinimumSize(QtCore.QSize(75, 23))
        self.btn_nav_network.setMaximumSize(QtCore.QSize(75, 23))
        self.btn_nav_network.setStyleSheet("border-style:None;\n"
"text-align: left center;")
        self.btn_nav_network.setObjectName("btn_nav_network")
        self.hLayout_network.addWidget(self.btn_nav_network)
        self.verticalLayout_2.addLayout(self.hLayout_network)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout.addWidget(self.frame)
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setMinimumSize(QtCore.QSize(250, 200))
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 550))
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setEnabled(True)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -764, 533, 1470))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(520, 1470))
        self.scrollAreaWidgetContents.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setMinimumSize(QtCore.QSize(520, 1470))
        self.widget.setMaximumSize(QtCore.QSize(500, 16777215))
        self.widget.setObjectName("widget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.group_General = QtWidgets.QGroupBox(self.widget)
        self.group_General.setMinimumSize(QtCore.QSize(300, 250))
        self.group_General.setMaximumSize(QtCore.QSize(16777215, 250))
        self.group_General.setObjectName("group_General")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.group_General)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.group_General)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 90))
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 90))
        self.groupBox_4.setObjectName("groupBox_4")
        self.chbx_start_at_boot = QtWidgets.QCheckBox(self.groupBox_4)
        self.chbx_start_at_boot.setGeometry(QtCore.QRect(20, 30, 161, 17))
        self.chbx_start_at_boot.setObjectName("chbx_start_at_boot")
        self.chbx_start_mini = QtWidgets.QCheckBox(self.groupBox_4)
        self.chbx_start_mini.setGeometry(QtCore.QRect(60, 50, 101, 17))
        self.chbx_start_mini.setObjectName("chbx_start_mini")
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.group_General)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 90))
        self.groupBox_5.setMaximumSize(QtCore.QSize(16777215, 90))
        self.groupBox_5.setObjectName("groupBox_5")
        self.chbx_enable_notifications = QtWidgets.QCheckBox(self.groupBox_5)
        self.chbx_enable_notifications.setGeometry(QtCore.QRect(20, 30, 321, 17))
        self.chbx_enable_notifications.setObjectName("chbx_enable_notifications")
        self.chbx_notify_only_inactive = QtWidgets.QCheckBox(self.groupBox_5)
        self.chbx_notify_only_inactive.setGeometry(QtCore.QRect(50, 60, 151, 17))
        self.chbx_notify_only_inactive.setObjectName("chbx_notify_only_inactive")
        self.verticalLayout_4.addWidget(self.groupBox_5)
        self.verticalLayout_8.addWidget(self.group_General)
        self.group_UI = QtWidgets.QGroupBox(self.widget)
        self.group_UI.setMinimumSize(QtCore.QSize(0, 250))
        self.group_UI.setMaximumSize(QtCore.QSize(16777215, 300))
        self.group_UI.setObjectName("group_UI")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.group_UI)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox = QtWidgets.QGroupBox(self.group_UI)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 90))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 90))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.chbx_confirm_delete = QtWidgets.QCheckBox(self.groupBox)
        self.chbx_confirm_delete.setObjectName("chbx_confirm_delete")
        self.verticalLayout_6.addWidget(self.chbx_confirm_delete)
        self.chbx_confirm_exit = QtWidgets.QCheckBox(self.groupBox)
        self.chbx_confirm_exit.setObjectName("chbx_confirm_exit")
        self.verticalLayout_6.addWidget(self.chbx_confirm_exit)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.group_UI)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 75))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 75))
        self.groupBox_2.setObjectName("groupBox_2")
        self.chbx_minimize_minimizes = QtWidgets.QCheckBox(self.groupBox_2)
        self.chbx_minimize_minimizes.setGeometry(QtCore.QRect(10, 40, 251, 17))
        self.chbx_minimize_minimizes.setObjectName("chbx_minimize_minimizes")
        self.chbx_close_minimizes = QtWidgets.QCheckBox(self.groupBox_2)
        self.chbx_close_minimizes.setGeometry(QtCore.QRect(10, 20, 201, 17))
        self.chbx_close_minimizes.setObjectName("chbx_close_minimizes")
        self.chbx_on_tray_clicked = QtWidgets.QCheckBox(self.groupBox_2)
        self.chbx_on_tray_clicked.setGeometry(QtCore.QRect(260, 20, 201, 17))
        self.chbx_on_tray_clicked.setObjectName("chbx_on_tray_clicked")
        self.verticalLayout_7.addWidget(self.groupBox_2)
        self.verticalLayout_8.addWidget(self.group_UI)
        self.group_directories = QtWidgets.QGroupBox(self.widget)
        self.group_directories.setMinimumSize(QtCore.QSize(0, 330))
        self.group_directories.setMaximumSize(QtCore.QSize(16777215, 330))
        self.group_directories.setObjectName("group_directories")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.group_directories)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox_6 = QtWidgets.QGroupBox(self.group_directories)
        self.groupBox_6.setMinimumSize(QtCore.QSize(0, 200))
        self.groupBox_6.setMaximumSize(QtCore.QSize(16777215, 200))
        self.groupBox_6.setObjectName("groupBox_6")
        self.combo_categories = QtWidgets.QComboBox(self.groupBox_6)
        self.combo_categories.setGeometry(QtCore.QRect(10, 50, 161, 22))
        self.combo_categories.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background: white;\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                 stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"}\n"
"\n"
"/* QComboBox gets the \"on\" state when the popup is open */\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #D3D3D3, stop: 0.4 #D8D8D8,\n"
"                                stop: 0.5 #DDDDDD, stop: 1.0 #E1E1E1);\n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(/usr/share/icons/crystalsvg/16x16/actions/1downarrow.png);\n"
"}\n"
"\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}")
        self.combo_categories.setObjectName("combo_categories")
        self.btn_add_category = QtWidgets.QPushButton(self.groupBox_6)
        self.btn_add_category.setGeometry(QtCore.QRect(180, 51, 21, 20))
        self.btn_add_category.setStyleSheet("border-image:url(./imgs/add_green.png);\n"
"border: solid green 2px;")
        self.btn_add_category.setText("")
        self.btn_add_category.setObjectName("btn_add_category")
        self.btn_del_category = QtWidgets.QPushButton(self.groupBox_6)
        self.btn_del_category.setGeometry(QtCore.QRect(210, 50, 21, 23))
        self.btn_del_category.setStyleSheet("border-image:url(./imgs/minus_red.png);")
        self.btn_del_category.setText("")
        self.btn_del_category.setObjectName("btn_del_category")
        self.label = QtWidgets.QLabel(self.groupBox_6)
        self.label.setGeometry(QtCore.QRect(10, 90, 141, 16))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.groupBox_6)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 47, 13))
        self.label_3.setObjectName("label_3")
        self.edit_extensions = QtWidgets.QLineEdit(self.groupBox_6)
        self.edit_extensions.setGeometry(QtCore.QRect(10, 110, 461, 20))
        self.edit_extensions.setObjectName("edit_extensions")
        self.label_4 = QtWidgets.QLabel(self.groupBox_6)
        self.label_4.setGeometry(QtCore.QRect(10, 140, 61, 16))
        self.label_4.setObjectName("label_4")
        self.edit_category_path = QtWidgets.QLineEdit(self.groupBox_6)
        self.edit_category_path.setGeometry(QtCore.QRect(10, 160, 421, 20))
        self.edit_category_path.setReadOnly(True)
        self.edit_category_path.setObjectName("edit_category_path")
        self.btn_browse_category_path = QtWidgets.QPushButton(self.groupBox_6)
        self.btn_browse_category_path.setGeometry(QtCore.QRect(440, 160, 31, 23))
        self.btn_browse_category_path.setObjectName("btn_browse_category_path")
        self.verticalLayout_9.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.group_directories)
        self.groupBox_7.setMinimumSize(QtCore.QSize(0, 60))
        self.groupBox_7.setMaximumSize(QtCore.QSize(16777215, 70))
        self.groupBox_7.setObjectName("groupBox_7")
        self.btn_browse_temp_dir = QtWidgets.QPushButton(self.groupBox_7)
        self.btn_browse_temp_dir.setGeometry(QtCore.QRect(440, 30, 31, 23))
        self.btn_browse_temp_dir.setObjectName("btn_browse_temp_dir")
        self.edit_temp_dir = QtWidgets.QLineEdit(self.groupBox_7)
        self.edit_temp_dir.setGeometry(QtCore.QRect(10, 30, 421, 20))
        self.edit_temp_dir.setReadOnly(True)
        self.edit_temp_dir.setObjectName("edit_temp_dir")
        self.verticalLayout_9.addWidget(self.groupBox_7)
        self.verticalLayout_8.addWidget(self.group_directories)
        self.group_browser = QtWidgets.QGroupBox(self.widget)
        self.group_browser.setEnabled(False)
        self.group_browser.setMinimumSize(QtCore.QSize(530, 300))
        self.group_browser.setMaximumSize(QtCore.QSize(500, 300))
        self.group_browser.setObjectName("group_browser")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.group_browser)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.groupBox_9 = QtWidgets.QGroupBox(self.group_browser)
        self.groupBox_9.setMinimumSize(QtCore.QSize(490, 120))
        self.groupBox_9.setMaximumSize(QtCore.QSize(490, 120))
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.chbx_chrome = QtWidgets.QCheckBox(self.groupBox_9)
        self.chbx_chrome.setEnabled(False)
        self.chbx_chrome.setObjectName("chbx_chrome")
        self.verticalLayout_11.addWidget(self.chbx_chrome)
        self.chbx_firefox = QtWidgets.QCheckBox(self.groupBox_9)
        self.chbx_firefox.setEnabled(False)
        self.chbx_firefox.setObjectName("chbx_firefox")
        self.verticalLayout_11.addWidget(self.chbx_firefox)
        self.chbx_edge = QtWidgets.QCheckBox(self.groupBox_9)
        self.chbx_edge.setEnabled(False)
        self.chbx_edge.setObjectName("chbx_edge")
        self.verticalLayout_11.addWidget(self.chbx_edge)
        self.chbx_opera = QtWidgets.QCheckBox(self.groupBox_9)
        self.chbx_opera.setEnabled(False)
        self.chbx_opera.setObjectName("chbx_opera")
        self.verticalLayout_11.addWidget(self.chbx_opera)
        self.verticalLayout_12.addWidget(self.groupBox_9)
        self.groupBox_10 = QtWidgets.QGroupBox(self.group_browser)
        self.groupBox_10.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_10.sizePolicy().hasHeightForWidth())
        self.groupBox_10.setSizePolicy(sizePolicy)
        self.groupBox_10.setMinimumSize(QtCore.QSize(490, 130))
        self.groupBox_10.setMaximumSize(QtCore.QSize(490, 130))
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.chbx_auto_start_browser_files = QtWidgets.QCheckBox(self.groupBox_10)
        self.chbx_auto_start_browser_files.setObjectName("chbx_auto_start_browser_files")
        self.verticalLayout_10.addWidget(self.chbx_auto_start_browser_files)
        self.label_5 = QtWidgets.QLabel(self.groupBox_10)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_10.addWidget(self.label_5)
        self.rbtn_alt_no_catch = QtWidgets.QRadioButton(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbtn_alt_no_catch.sizePolicy().hasHeightForWidth())
        self.rbtn_alt_no_catch.setSizePolicy(sizePolicy)
        self.rbtn_alt_no_catch.setMinimumSize(QtCore.QSize(0, 0))
        self.rbtn_alt_no_catch.setObjectName("rbtn_alt_no_catch")
        self.verticalLayout_10.addWidget(self.rbtn_alt_no_catch)
        self.rbtn_alt_catch = QtWidgets.QRadioButton(self.groupBox_10)
        self.rbtn_alt_catch.setObjectName("rbtn_alt_catch")
        self.verticalLayout_10.addWidget(self.rbtn_alt_catch)
        self.chbx_auto_start_browser_files.raise_()
        self.label_5.raise_()
        self.rbtn_alt_catch.raise_()
        self.rbtn_alt_no_catch.raise_()
        self.verticalLayout_12.addWidget(self.groupBox_10)
        self.verticalLayout_8.addWidget(self.group_browser)
        self.group_network = QtWidgets.QGroupBox(self.widget)
        self.group_network.setMinimumSize(QtCore.QSize(510, 300))
        self.group_network.setMaximumSize(QtCore.QSize(510, 16777215))
        self.group_network.setObjectName("group_network")
        self.groupBox_12 = QtWidgets.QGroupBox(self.group_network)
        self.groupBox_12.setGeometry(QtCore.QRect(10, 30, 491, 241))
        self.groupBox_12.setMinimumSize(QtCore.QSize(490, 240))
        self.groupBox_12.setObjectName("groupBox_12")
        self.rbtn_system_proxy = QtWidgets.QRadioButton(self.groupBox_12)
        self.rbtn_system_proxy.setGeometry(QtCore.QRect(10, 20, 111, 21))
        self.rbtn_system_proxy.setChecked(True)
        self.rbtn_system_proxy.setObjectName("rbtn_system_proxy")
        self.rbtn_no_proxy = QtWidgets.QRadioButton(self.groupBox_12)
        self.rbtn_no_proxy.setGeometry(QtCore.QRect(10, 50, 82, 17))
        self.rbtn_no_proxy.setObjectName("rbtn_no_proxy")
        self.rbtn_manual_proxy = QtWidgets.QRadioButton(self.groupBox_12)
        self.rbtn_manual_proxy.setGeometry(QtCore.QRect(10, 80, 131, 17))
        self.rbtn_manual_proxy.setObjectName("rbtn_manual_proxy")
        self.label_2 = QtWidgets.QLabel(self.groupBox_12)
        self.label_2.setGeometry(QtCore.QRect(10, 130, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_12)
        self.label_6.setGeometry(QtCore.QRect(10, 160, 47, 13))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_12)
        self.label_7.setGeometry(QtCore.QRect(10, 190, 47, 13))
        self.label_7.setObjectName("label_7")
        self.edit_http_address = QtWidgets.QLineEdit(self.groupBox_12)
        self.edit_http_address.setEnabled(False)
        self.edit_http_address.setGeometry(QtCore.QRect(60, 130, 113, 20))
        self.edit_http_address.setClearButtonEnabled(False)
        self.edit_http_address.setObjectName("edit_http_address")
        self.edit_http_port = QtWidgets.QLineEdit(self.groupBox_12)
        self.edit_http_port.setEnabled(False)
        self.edit_http_port.setGeometry(QtCore.QRect(180, 130, 61, 20))
        self.edit_http_port.setObjectName("edit_http_port")
        self.edit_http_password = QtWidgets.QLineEdit(self.groupBox_12)
        self.edit_http_password.setEnabled(False)
        self.edit_http_password.setGeometry(QtCore.QRect(370, 130, 113, 20))
        self.edit_http_password.setObjectName("edit_http_password")
        self.edit_http_user = QtWidgets.QLineEdit(self.groupBox_12)
        self.edit_http_user.setEnabled(False)
        self.edit_http_user.setGeometry(QtCore.QRect(250, 130, 113, 20))
        self.edit_http_user.setObjectName("edit_http_user")
        self.edit_https_address = QtWidgets.QLineEdit(self.groupBox_12)
        self.edit_https_address.setEnabled(False)
        self.edit_https_address.setGeometry(QtCore.QRect(60, 160, 113, 20))
        self.edit_https_address.setObjectName("edit_https_address")
        self.edit_ftp_address = QtWidgets.QLineEdit(self.groupBox_12)
        self.edit_ftp_address.setEnabled(False)
        self.edit_ftp_address.setGeometry(QtCore.QRect(60, 190, 113, 20))
        self.edit_ftp_address.setObjectName("edit_ftp_address")
        self.edit_https_user = QtWidgets.QLineEdit(self.groupBox_12)
        self.edit_https_user.setEnabled(False)
        self.edit_https_user.setGeometry(QtCore.QRect(250, 160, 113, 20))
        self.edit_https_user.setObjectName("edit_https_user")
        self.edit_ftp_password = QtWidgets.QLineEdit(self.groupBox_12)
        self.edit_ftp_password.setEnabled(False)
        self.edit_ftp_password.setGeometry(QtCore.QRect(370, 190, 113, 20))
        self.edit_ftp_password.setObjectName("edit_ftp_password")
        self.edit_ftp_user = QtWidgets.QLineEdit(self.groupBox_12)
        self.edit_ftp_user.setEnabled(False)
        self.edit_ftp_user.setGeometry(QtCore.QRect(250, 190, 113, 20))
        self.edit_ftp_user.setObjectName("edit_ftp_user")
        self.edit_https_password = QtWidgets.QLineEdit(self.groupBox_12)
        self.edit_https_password.setEnabled(False)
        self.edit_https_password.setGeometry(QtCore.QRect(370, 160, 113, 20))
        self.edit_https_password.setObjectName("edit_https_password")
        self.edit_https_port = QtWidgets.QLineEdit(self.groupBox_12)
        self.edit_https_port.setEnabled(False)
        self.edit_https_port.setGeometry(QtCore.QRect(180, 160, 61, 20))
        self.edit_https_port.setObjectName("edit_https_port")
        self.edit_ftp_port = QtWidgets.QLineEdit(self.groupBox_12)
        self.edit_ftp_port.setEnabled(False)
        self.edit_ftp_port.setGeometry(QtCore.QRect(180, 190, 61, 20))
        self.edit_ftp_port.setObjectName("edit_ftp_port")
        self.label_8 = QtWidgets.QLabel(self.groupBox_12)
        self.label_8.setGeometry(QtCore.QRect(80, 110, 47, 13))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_12)
        self.label_9.setGeometry(QtCore.QRect(190, 110, 47, 13))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_12)
        self.label_10.setGeometry(QtCore.QRect(280, 110, 47, 13))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_12)
        self.label_11.setGeometry(QtCore.QRect(400, 110, 47, 13))
        self.label_11.setObjectName("label_11")
        self.verticalLayout_8.addWidget(self.group_network)
        self.verticalLayout_5.addWidget(self.widget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)

        self.retranslateUi(Form)
        self.rbtn_manual_proxy.toggled['bool'].connect(self.edit_ftp_address.setEnabled)
        self.rbtn_manual_proxy.toggled['bool'].connect(self.edit_ftp_password.setEnabled)
        self.rbtn_manual_proxy.toggled['bool'].connect(self.edit_ftp_port.setEnabled)
        self.rbtn_manual_proxy.toggled['bool'].connect(self.edit_ftp_user.setEnabled)
        self.rbtn_manual_proxy.toggled['bool'].connect(self.edit_http_address.setEnabled)
        self.rbtn_manual_proxy.toggled['bool'].connect(self.edit_http_password.setEnabled)
        self.rbtn_manual_proxy.toggled['bool'].connect(self.edit_http_port.setEnabled)
        self.rbtn_manual_proxy.toggled['bool'].connect(self.edit_http_user.setEnabled)
        self.rbtn_manual_proxy.toggled['bool'].connect(self.edit_https_address.setEnabled)
        self.rbtn_manual_proxy.toggled['bool'].connect(self.edit_https_port.setEnabled)
        self.rbtn_manual_proxy.toggled['bool'].connect(self.edit_https_password.setEnabled)
        self.rbtn_manual_proxy.toggled['bool'].connect(self.edit_https_user.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "User Preferences"))
        self.btn_nav_gen.setText(_translate("Form", "General"))
        self.btn_nav_ui.setText(_translate("Form", "User Interface"))
        self.btn_nav_directories.setText(_translate("Form", "Directories"))
        self.btn_nav_browser.setText(_translate("Form", "Browser"))
        self.btn_nav_network.setText(_translate("Form", "Network"))
        self.group_General.setTitle(_translate("Form", "General"))
        self.groupBox_4.setTitle(_translate("Form", "Windows Integration"))
        self.chbx_start_at_boot.setText(_translate("Form", "Start when Windows starts"))
        self.chbx_start_mini.setText(_translate("Form", "Start minimized"))
        self.groupBox_5.setTitle(_translate("Form", "Notifications"))
        self.chbx_enable_notifications.setText(_translate("Form", "Notify me of completed downloads via Notification Center"))
        self.chbx_notify_only_inactive.setText(_translate("Form", "Only when QDM is inactive"))
        self.group_UI.setTitle(_translate("Form", "User Interface"))
        self.groupBox.setTitle(_translate("Form", "Display Options"))
        self.chbx_confirm_delete.setText(_translate("Form", "Confirm when deleting downloads"))
        self.chbx_confirm_exit.setText(_translate("Form", "Confirm dialog on exit"))
        self.groupBox_2.setTitle(_translate("Form", "System Tray"))
        self.chbx_minimize_minimizes.setText(_translate("Form", "Minimize button minimizes window to tray"))
        self.chbx_close_minimizes.setText(_translate("Form", "Close button minimizes window to tray"))
        self.chbx_on_tray_clicked.setText(_translate("Form", "Always restore window when clicked"))
        self.group_directories.setTitle(_translate("Form", "Directories"))
        self.groupBox_6.setTitle(_translate("Form", "Output Directories"))
        self.label.setText(_translate("Form", "Associated Extensions"))
        self.label_3.setText(_translate("Form", "Category"))
        self.label_4.setText(_translate("Form", "Path"))
        self.btn_browse_category_path.setText(_translate("Form", "..."))
        self.groupBox_7.setTitle(_translate("Form", "Temporary Directory"))
        self.btn_browse_temp_dir.setText(_translate("Form", "..."))
        self.group_browser.setTitle(_translate("Form", "Browser Integration"))
        self.groupBox_9.setTitle(_translate("Form", "Browsers"))
        self.chbx_chrome.setText(_translate("Form", "Chrome"))
        self.chbx_firefox.setText(_translate("Form", "Firefox"))
        self.chbx_edge.setText(_translate("Form", "Edge"))
        self.chbx_opera.setText(_translate("Form", "Opera"))
        self.groupBox_10.setTitle(_translate("Form", "Configuration"))
        self.chbx_auto_start_browser_files.setText(_translate("Form", "Automatically start downloads without confirmation"))
        self.label_5.setText(_translate("Form", "Using Alt Key"))
        self.rbtn_alt_no_catch.setText(_translate("Form", "Don\'t catch downloads when Alt key is pressed"))
        self.rbtn_alt_catch.setText(_translate("Form", "Only catch downloads when Alt key is pressed"))
        self.group_network.setTitle(_translate("Form", "Network"))
        self.groupBox_12.setTitle(_translate("Form", "Proxy"))
        self.rbtn_system_proxy.setText(_translate("Form", "Use system proxy"))
        self.rbtn_no_proxy.setText(_translate("Form", "No proxy"))
        self.rbtn_manual_proxy.setText(_translate("Form", "Manual configuration"))
        self.label_2.setText(_translate("Form", "HTTP"))
        self.label_6.setText(_translate("Form", "HTTPS"))
        self.label_7.setText(_translate("Form", "FTP"))
        self.label_8.setText(_translate("Form", "Address"))
        self.label_9.setText(_translate("Form", "Port"))
        self.label_10.setText(_translate("Form", "Username"))
        self.label_11.setText(_translate("Form", "Password"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())